spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/res/, classpath:/img/

student:
  email: 120844@qq.com
  name: jack-yml
  age: ${custom.num2:87} #yml文件中引用properties中的配置 ${custom.num2}没有，原样输出，可以写一个默认值
  birthday: 2018/08/26
  locations: {province: 安徽, city: 合肥, zoom: 包河}
  skills:
    - 编程
    - 送外卖
  hobbies:
    - 游戏
    - 足球
  pet: {strain: 哈士奇2, nickname: 旺财678}
#    strain: 哈士奇2
#    nickname: 旺财678

server:
  port: 9527
  servlet:
#    ContextPath must start with '/' and not end with '/'
#    context-path: boot
    context-path: /boot

# 设置日志级别
logging:
  level:
    com.netease.accidence: warn
# 日志文件
#  file:
    #springboot.log # 相对路径，此时日志文件生成在项目的根目录中
#    /Users/dingzhaohua/logs/neteaseSpringBoot.log # 绝对路径
  path:  /Users/dingzhaohua/logs/

#一个yml文件中可以写多个配置文件，配置文件之间用 --- 分割
#建议写成多个文件 xxx-dev.yml xxx-prod.yml

---

spring:
  profiles: prod

server:
  port: 9528

---

spring:
  profiles: dev
student:
  name: jack-dev-yml

server:
  port: 9529

# 动态指定环境
#  i: 命令行方式 --spring.profiles.active=dev 在编辑器中设置，具体看有道云笔记

# 项目内部配置文件的位置（application.properties、application.yml）有四个地方，若动态指定的话，注意优先级会调整
# 项目根目录/config
# 项目根目录
# classpath/config
# classpath
