spring:
  profiles:
    active: prod

student:
  name: jack
  age: 18
  birthday: 2018/08/26
  locations: {province: 安徽, city: 合肥, zoom: 包河}
  skills:
  - 编程
  - 送外卖
  hobbies:
  - 游戏
  - 足球
  pet:
    nickName: 旺财
    strain: 哈士奇